---
#PUT here your main variable
project_name: caspr
port: 80
apt_specific_packages:
  - git

update_apt_cache: yes

nodejs_version: "10.x"
certbot_admin_email: "nicolasb@theodo.fr"

# List of databases to be created
postgresql_databases:
  - name: caspr

# List of users to be created
postgresql_users:
  - name: caspr
    password: caspr
